### ISSUE TITLE
Error occurred while generating styles (with saadeghi / daisyui)

### ISSUE THREAD

**Issue by IamLizu** [vadimdemedes/tailwind-rn#106]
I tried to install [daisyUI](https://github.com/saadeghi/daisyui) in my project. And when I tried to generate style.json wtih `npx create-tailwind-rn`, I got,
```
Error: Failed to parse declaration "borderRadius: var(--rounded-box,1rem)"
    at transformShorthandValue (E:\react-native-1\project1\node_modules\css-to-react-native\index.js:825:11)
    at getStylesForProperty (E:\react-native-1\project1\node_modules\css-to-react-native\index.js:834:109)
    at E:\react-native-1\project1\node_modules\css-to-react-native\index.js:857:33
    at Array.reduce (<anonymous>)
    at index (E:\react-native-1\project1\node_modules\css-to-react-native\index.js:853:16)
    at getStyles (E:\react-native-1\project1\node_modules\tailwind-rn\build.js:25:9)
    at module.exports (E:\react-native-1\project1\node_modules\tailwind-rn\build.js:165:24)
    at E:\react-native-1\project1\node_modules\tailwind-rn\cli.js:22:18
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

I am new to react-native. I am not sure if I am missing something.

**Comment by heymartinadams** [comment]
@IamLizu I’m running into the same issue. Have you been able to either solve it, or pinpoint the cause?
