### ISSUE TITLE
npx setup tailwind-rn throws Error: Cannot find module 'postcss'

### ISSUE THREAD

**Issue by afkcodes** [vadimdemedes/tailwind-rn#132]
```
npx setup-tailwind-rn

  ✔ Install dependencies
  ✖ Create Tailwind config
    → info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
    Add scripts
Error: Command failed with exit code 1: yarn tailwindcss init
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'postcss'
Require stack:
- /Users/ashish/projects/tarana/node_modules/tailwindcss/lib/lib/generateRules.js
- /Users/ashish/projects/tarana/node_modules/tailwindcss/lib/lib/expandTailwindAtRules.js
- /Users/ashish/projects/tarana/node_modules/tailwindcss/lib/processTailwindFeatures.js
- /Users/ashish/projects/tarana/node_modules/tailwindcss/lib/cli.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/ashish/projects/tarana/node_modules/tailwindcss/lib/lib/generateRules.js:6:39)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/ashish/projects/tarana/node_modules/tailwindcss/lib/lib/generateRules.js',
    '/Users/ashish/projects/tarana/node_modules/tailwindcss/lib/lib/expandTailwindAtRules.js',
    '/Users/ashish/projects/tarana/node_modules/tailwindcss/lib/processTailwindFeatures.js',
    '/Users/ashish/projects/tarana/node_modules/tailwindcss/lib/cli.js'
  ]
}
error Command failed with exit code 1.
yarn run v1.22.11
$ /Users/ashish/projects/tarana/node_modules/.bin/tailwindcss init
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
    at makeError (file:///Users/ashish/.npm/_npx/fce68b938067d432/node_modules/execa/lib/error.js:59:11)
    at handlePromise (file:///Users/ashish/.npm/_npx/fce68b938067d432/node_modules/execa/index.js:119:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Task.task (file:///Users/ashish/.npm/_npx/fce68b938067d432/node_modules/setup-tailwind-rn/cli.js:46:4)
```

**Comment by shoxie** [comment]
you can install postcss, then tun the script again

**Comment by jonsamp** [comment]
I posted setup steps here that might help: https://github.com/vadimdemedes/tailwind-rn/issues/128#issuecomment-1019372506

**Comment by vadimdemedes** [comment]
Hm, interesting why I didn't get the same error. Going to update instructions and CLI to install `postcss` then.

**Comment by nathanguigui** [comment]
Hello do you think it's possible to provide a default `tailwind.json` file ?

**Comment by vadimdemedes** [comment]
@nathanguigui What for?

**Comment by nathanguigui** [comment]
for those who would like to use the package without generating their own config
also when I tried to generate the utilities I saw that some rules where missing like padding margin, etc..
I was using the version 3 and I think version 4 is more difficult to use than the version 3, that why I ask you for a default `tailwind.json` in the project.
I think that can be easier  with this default file

**Comment by vadimdemedes** [comment]
That's not possible anymore, because Tailwind v4 only has a JIT compiler, which includes only utilities that you have in your codebase.

**Comment by vadimdemedes** [comment]
@afkcodes Actually, do you have `postcss.config.js` in your project? I keep wondering why I don't get the same error about `postcss`. `setup-tailwind-rn` works fine without it for me.

**Comment by vadimdemedes** [comment]
Ok, just saw this on CI. I suspect on my machine I have the latest npm, which installs peer dependencies (`tailwindcss` has `postcss` specified as a peer dependency), but CI doesn't.

**Comment by vadimdemedes** [comment]
Should be fixed in the latest versions of `tailwind-rn` and `setup-tailwind-rn` now.
