### ISSUE TITLE
CSS to JSON parsing breaks with multiple font-family styles

### ISSUE THREAD

**Issue by yTakkar** [vadimdemedes/tailwind-rn#137]
I have a tailwind config and its font-family object looks something like this

```js
fontFamily: {
      primary: ['"BentonSans"', 'Arial', 'Noto Sans', 'sans-serif'],
      'primary-bold': ['"BentonSans-Bold"', 'Arial', 'Noto Sans', 'sans-serif'],
      'primary-medium': ['"BentonSans-Medium"', 'Arial', 'Noto Sans', 'sans-serif'],
},
```

This is the error I get
```bash
> own-store-mini-app-rn@1.0.0 tailwind:config:json /Users/faiyazshaikh/Projects/Personal/own-store/own-store-mini-app-rn
> tailwind-rn -i styles/tailwind.css -o styles/tailwind.json

/Users/faiyazshaikh/Projects/Personal/own-store/own-store-mini-app-rn/node_modules/css-to-react-native/index.js:825
    throw new Error("Failed to parse declaration \"" + propName + ": " + value + "\"");
    ^

Error: Failed to parse declaration "fontFamily: "BentonSans", Arial, Noto Sans, sans-serif"
    at transformShorthandValue (/Users/faiyazshaikh/Projects/Personal/own-store/own-store-mini-app-rn/node_modules/css-to-react-native/index.js:825:11)
    at getStylesForProperty (/Users/faiyazshaikh/Projects/Personal/own-store/own-store-mini-app-rn/node_modules/css-to-react-native/index.js:834:109)
    at /Users/faiyazshaikh/Projects/Personal/own-store/own-store-mini-app-rn/node_modules/css-to-react-native/index.js:857:33
    at Array.reduce (<anonymous>)
    at index (/Users/faiyazshaikh/Projects/Personal/own-store/own-store-mini-app-rn/node_modules/css-to-react-native/index.js:853:16)
    at getStyle (/Users/faiyazshaikh/Projects/Personal/own-store/own-store-mini-app-rn/node_modules/tailwind-rn/dist/build.js:14:46)
    at addRule (/Users/faiyazshaikh/Projects/Personal/own-store/own-store-mini-app-rn/node_modules/tailwind-rn/dist/build.js:30:24)
    at build (/Users/faiyazshaikh/Projects/Personal/own-store/own-store-mini-app-rn/node_modules/tailwind-rn/dist/build.js:37:13)
    at build (/Users/faiyazshaikh/Projects/Personal/own-store/own-store-mini-app-rn/node_modules/tailwind-rn/dist/cli.js:49:43)
    at Object.<anonymous> (/Users/faiyazshaikh/Projects/Personal/own-store/own-store-mini-app-rn/node_modules/tailwind-rn/dist/cli.js:56:5)
```

Or is there something I'm missing here?

**Comment by vadimdemedes** [comment]
Does React Native support font definitions like that, with multiple font families? I thought it doesn't.

**Comment by yTakkar** [comment]
Yes, I'm kind of new to RN, I think it doesn't (after going through various posts). We can mark it as invalid.
