### ISSUE TITLE
Error: Failed to parse declaration "fontFamily: 'some font',sans-serif"

### ISSUE THREAD

**Issue by rory-ferguson** [vadimdemedes/tailwind-rn#165]
I started a new envo react native project and tried to install tailwind-rn

I'm getting an error where tailwind-rn is compiling the `tailwind.css` from the `input.css` and it's pulling in a `"fontFamily: 'some font',sans-serif"` directly from `@tailwind utilities;` it looks like

ERROR

```
concurrently "tailwindcss --input input.css --output tailwind.css --no-autoprefixer --watch" "tailwind-rn --watch"

[1] Error: Failed to parse declaration "fontFamily: 'some font',sans-serif"
[1]     at transformShorthandValue (/Users/roryferguson/Documents/Repositories/practice/AwesomeProject/node_modules/css-to-react-native/index.js:825:11)
[1]     at getStylesForProperty (/Users/roryferguson/Documents/Repositories/practice/AwesomeProject/node_modules/css-to-react-native/index.js:834:109)
[1]     at /Users/roryferguson/Documents/Repositories/practice/AwesomeProject/node_modules/css-to-react-native/index.js:857:33
[1]     at Array.reduce (<anonymous>)
[1]     at index (/Users/roryferguson/Documents/Repositories/practice/AwesomeProject/node_modules/css-to-react-native/index.js:853:16)
[1]     at getStyle (/Users/roryferguson/Documents/Repositories/practice/AwesomeProject/node_modules/tailwind-rn/dist/build.js:16:46)
[1]     at addRule (/Users/roryferguson/Documents/Repositories/practice/AwesomeProject/node_modules/tailwind-rn/dist/build.js:32:24)
[1]     at build (/Users/roryferguson/Documents/Repositories/practice/AwesomeProject/node_modules/tailwind-rn/dist/build.js:39:13)
[1]     at FSWatcher.build (/Users/roryferguson/Documents/Repositories/practice/AwesomeProject/node_modules/tailwind-rn/dist/cli.js:49:43)
[1]     at FSWatcher.emit (node:events:520:28)
[1] tailwind-rn --watch exited with code 1
```

input.css
```
@tailwind utilities;
```
tailwind.css

```
...

.font-\[\'some_font\'\2c sans-serif\] {
  font-family: 'some font',sans-serif
}

.font-\[\"some_font\"\2c sans-serif\] {
  font-family: "some font",sans-serif
}

...
```

tailwind.json
```
{}
```

tailwind.config.js
```
module.exports = {
  content: ['./**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {},
  },
  plugins: [],
  corePlugins: require('tailwind-rn/unsupported-core-plugins'),
}
```

```
{
  "name": "awesomeproject",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject",
    "build:tailwind": "tailwindcss --input input.css --output tailwind.css --no-autoprefixer && tailwind-rn",
    "dev:tailwind": "concurrently \"tailwindcss --input input.css --output tailwind.css --no-autoprefixer --watch\" \"tailwind-rn --watch\""
  },
  "dependencies": {
    "@react-native-async-storage/async-storage": "^1.17.3",
    "@react-native-community/netinfo": "^8.2.0",
    "@react-native-picker/picker": "^2.4.1",
    "aws-amplify": "^4.3.20",
    "aws-amplify-react-native": "^6.0.4",
    "expo": "~44.0.0",
    "expo-status-bar": "~1.2.0",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-native": "0.64.3",
    "react-native-web": "0.17.1",
    "tailwind-rn": "^4.2.0"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "concurrently": "^7.1.0",
    "postcss": "^8.4.12",
    "tailwindcss": "^3.0.24"
  },
  "private": true
}
```

**Comment by heymartinadams** [comment]
This seems related to https://github.com/vadimdemedes/tailwind-rn/issues/106 (no solution yet).

**Comment by vadimdemedes** [comment]
React Native requires a specific font name in there. CSS-like font fallbacks aren't supported, e.g. `Inter, Helvetica, sans-serif`.
