### ISSUE TITLE
Unsupported Tailwind class, not responding on rect native

### ISSUE THREAD

**Issue by gmako6** [vadimdemedes/tailwind-rn#187]
<img width="715" alt="Screen Shot 2022-10-16 at 10 24 12 AM" src="https://user-images.githubusercontent.com/37672372/196023659-e55ea66e-0ed2-4563-9b8f-ff482f733702.png">

![Screen Shot 2022-10-16 at 10 27 30 AM](https://user-images.githubusercontent.com/37672372/196023754-17899035-20a9-4b49-b5db-dc6da090e918.png)

Unsupported Tailwind class: "h-full"
at node_modules/tailwind-rn/dist/create.js:35:28 in tailwind
at Home.js:9:37 in Home
at node_modules/react-native/Libraries/ReactNative/renderApplication.js:80:51 in renderApplication
at node_modules/react-native/Libraries/ReactNative/AppRegistry.js:119:25 in runnables.appKey.run
at node_modules/react-native/Libraries/ReactNative/AppRegistry.js:213:25 in runApplication

Unsupported Tailwind class: "pt-12"
at node_modules/tailwind-rn/dist/create.js:35:28 in tailwind
at Home.js:11:31 in Home
at node_modules/react-native/Libraries/ReactNative/renderApplication.js:80:51 in renderApplication
at node_modules/react-native/Libraries/ReactNative/AppRegistry.js:119:25 in runnables.appKey.run
at node_modules/react-native/Libraries/ReactNative/AppRegistry.js:213:25 in runApplication

Unsupported Tailwind class: "items-center"
at node_modules/tailwind-rn/dist/create.js:35:28 in tailwind
at Home.js:11:31 in Home
at node_modules/react-native/Libraries/ReactNative/renderApplication.js:80:51 in renderApplication
at node_modules/react-native/Libraries/ReactNative/AppRegistry.js:119:25 in runnables.appKey.run
at node_modules/react-native/Libraries/ReactNative/AppRegistry.js:213:25 in runApplication

Unsupported Tailwind class: "rounded-full"
at node_modules/tailwind-rn/dist/create.js:35:28 in tailwind
at Home.js:12:33 in Home
at node_modules/react-native/Libraries/ReactNative/renderApplication.js:80:51 in renderApplication
at node_modules/react-native/Libraries/ReactNative/AppRegistry.js:119:25 in runnables.appKey.run
at node_modules/react-native/Libraries/ReactNative/AppRegistry.js:213:25 in runApplication

Unsupported Tailwind class: "px-3"
at node_modules/tailwind-rn/dist/create.js:35:28 in tailwind
at Home.js:12:33 in Home
at node_modules/react-native/Libraries/ReactNative/renderApplication.js:80:51 in renderApplication
at node_modules/react-native/Libraries/ReactNative/AppRegistry.js:119:25 in runnables.appKey.run
at node_modules/react-native/Libraries/ReactNative/AppRegistry.js:213:25 in runApplication

Unsupported Tailwind class: "py-1"
at node_modules/tailwind-rn/dist/create.js:35:28 in tailwind
at Home.js:12:33 in Home
at node_modules/react-native/Libraries/ReactNative/renderApplication.js:80:51 in renderApplication
at node_modules/react-native/Libraries/ReactNative/AppRegistry.js:119:25 in runnables.appKey.run
at node_modules/react-native/Libraries/ReactNative/AppRegistry.js:213:25 in runApplication

Unsupported Tailwind class: "bg-blue-200"
at node_modules/tailwind-rn/dist/create.js:35:28 in tailwind
at Home.js:12:33 in Home
at node_modules/react-native/Libraries/ReactNative/renderApplication.js:80:51 in renderApplication
at node_modules/react-native/Libraries/ReactNative/AppRegistry.js:119:25 in runnables.appKey.run
at node_modules/react-native/Libraries/ReactNative/AppRegistry.js:213:25 in runApplication

Unsupported Tailwind class: "text-blue-600"
at node_modules/tailwind-rn/dist/create.js:35:28 in tailwind
at Home.js:13:35 in Home
at node_modules/react-native/Libraries/ReactNative/renderApplication.js:80:51 in renderApplication
at node_modules/react-native/Libraries/ReactNative/AppRegistry.js:119:25 in runnables.appKey.run
at node_modules/react-native/Libraries/ReactNative/AppRegistry.js:213:25 in runApplication

Unsupported Tailwind class: "h-full"
at node_modules/tailwind-rn/dist/create.js:35:28 in tailwind
at Home.js:9:37 in Home

Unsupported Tailwind class: "items-center"
at node_modules/tailwind-rn/dist/create.js:35:28 in tailwind
at Home.js:11:31 in Home

Unsupported Tailwind class: "pt-12"
at node_modules/tailwind-rn/dist/create.js:35:28 in tailwind
at Home.js:11:31 in Home

Unsupported Tailwind class: "bg-blue-200"
at node_modules/tailwind-rn/dist/create.js:35:28 in tailwind
at Home.js:12:33 in Home

Unsupported Tailwind class: "px-3"
at node_modules/tailwind-rn/dist/create.js:35:28 in tailwind
at Home.js:12:33 in Home

Unsupported Tailwind class: "rounded-full"
at node_modules/tailwind-rn/dist/create.js:35:28 in tailwind
at Home.js:12:33 in Home

Unsupported Tailwind class: "text-blue-600"
at node_modules/tailwind-rn/dist/create.js:35:28 in tailwind
at Home.js:13:35 in Home

Unsupported Tailwind class: "py-1"
at node_modules/tailwind-rn/dist/create.js:35:28 in tailwind
at Home.js:12:33 in Home

Unsupported Tailwind class: "h-full"
at node_modules/tailwind-rn/dist/create.js:35:28 in tailwind
at node_modules/react-native/Libraries/Core/setUpReactRefresh.js:43:45 in Refresh.performReactRefresh
at node_modules/metro-runtime/src/polyfills/require.js:645:37 in setTimeout$argument_0

Unsupported Tailwind class: "pt-12"
at node_modules/tailwind-rn/dist/create.js:35:28 in tailwind
at node_modules/react-native/Libraries/Core/setUpReactRefresh.js:43:45 in Refresh.performReactRefresh
at node_modules/metro-runtime/src/polyfills/require.js:645:37 in setTimeout$argument_0

Unsupported Tailwind class: "items-center"
at node_modules/tailwind-rn/dist/create.js:35:28 in tailwind
at node_modules/react-native/Libraries/Core/setUpReactRefresh.js:43:45 in Refresh.performReactRefresh
at node_modules/metro-runtime/src/polyfills/require.js:645:37 in setTimeout$argument_0

Unsupported Tailwind class: "px-3"
at node_modules/tailwind-rn/dist/create.js:35:28 in tailwind
at node_modules/react-native/Libraries/Core/setUpReactRefresh.js:43:45 in Refresh.performReactRefresh
at node_modules/metro-runtime/src/polyfills/require.js:645:37 in setTimeout$argument_0

Unsupported Tailwind class: "bg-blue-200"
at node_modules/tailwind-rn/dist/create.js:35:28 in tailwind
at node_modules/react-native/Libraries/Core/setUpReactRefresh.js:43:45 in Refresh.performReactRefresh
at node_modules/metro-runtime/src/polyfills/require.js:645:37 in setTimeout$argument_0

Unsupported Tailwind class: "text-blue-600"
at node_modules/tailwind-rn/dist/create.js:35:28 in tailwind
at node_modules/react-native/Libraries/Core/setUpReactRefresh.js:43:45 in Refresh.performReactRefresh
at node_modules/metro-runtime/src/polyfills/require.js:645:37 in setTimeout$argument_0

Unsupported Tailwind class: "py-1"
at node_modules/tailwind-rn/dist/create.js:35:28 in tailwind
at node_modules/react-native/Libraries/Core/setUpReactRefresh.js:43:45 in Refresh.performReactRefresh
at node_modules/metro-runtime/src/polyfills/require.js:645:37 in setTimeout$argument_0

Unsupported Tailwind class: "rounded-full"
at node_modules/tailwind-rn/dist/create.js:35:28 in tailwind
at node_modules/react-native/Libraries/Core/setUpReactRefresh.js:43:45 in Refresh.performReactRefresh
at node_modules/metro-runtime/src/polyfills/require.js:645:37 in setTimeout$argument_0

Unsupported Tailwind class: "h-full"
at node_modules/tailwind-rn/dist/create.js:35:28 in tailwind
at node_modules/react-native/Libraries/Core/setUpReactRefresh.js:43:45 in Refresh.performReactRefresh
at node_modules/metro-runtime/src/polyfills/require.js:645:37 in setTimeout$argument_0

Unsupported Tailwind class: "pt-12"
at node_modules/tailwind-rn/dist/create.js:35:28 in tailwind
at node_modules/react-native/Libraries/Core/setUpReactRefresh.js:43:45 in Refresh.performReactRefresh
at node_modules/metro-runtime/src/polyfills/require.js:645:37 in setTimeout$argument_0

Unsupported Tailwind class: "items-center"
at node_modules/tailwind-rn/dist/create.js:35:28 in tailwind
at node_modules/react-native/Libraries/Core/setUpReactRefresh.js:43:45 in Refresh.performReactRefresh
at node_modules/metro-runtime/src/polyfills/require.js:645:37 in setTimeout$argument_0

Unsupported Tailwind class: "bg-blue-200"
at node_modules/tailwind-rn/dist/create.js:35:28 in tailwind
at node_modules/react-native/Libraries/Core/setUpReactRefresh.js:43:45 in Refresh.performReactRefresh
at node_modules/metro-runtime/src/polyfills/require.js:645:37 in setTimeout$argument_0

Unsupported Tailwind class: "py-1"
at node_modules/tailwind-rn/dist/create.js:35:28 in tailwind
at node_modules/react-native/Libraries/Core/setUpReactRefresh.js:43:45 in Refresh.performReactRefresh
at node_modules/metro-runtime/src/polyfills/require.js:645:37 in setTimeout$argument_0

Unsupported Tailwind class: "px-3"
at node_modules/tailwind-rn/dist/create.js:35:28 in tailwind
at node_modules/react-native/Libraries/Core/setUpReactRefresh.js:43:45 in Refresh.performReactRefresh
at node_modules/metro-runtime/src/polyfills/require.js:645:37 in setTimeout$argument_0

Unsupported Tailwind class: "rounded-full"
at node_modules/tailwind-rn/dist/create.js:35:28 in tailwind
at node_modules/react-native/Libraries/Core/setUpReactRefresh.js:43:45 in Refresh.performReactRefresh
at node_modules/metro-runtime/src/polyfills/require.js:645:37 in setTimeout$argument_0

Unsupported Tailwind class: "text-blue-600"
at node_modules/tailwind-rn/dist/create.js:35:28 in tailwind
at node_modules/react-native/Libraries/Core/setUpReactRefresh.js:43:45 in Refresh.performReactRefresh
at node_modules/metro-runtime/src/polyfills/require.js:645:37 in setTimeout$argument_0

Unsupported Tailwind class: "h-full"
at node_modules/tailwind-rn/dist/create.js:35:28 in tailwind
at node_modules/react-native/Libraries/Core/setUpReactRefresh.js:43:45 in Refresh.performReactRefresh
at node_modules/metro-runtime/src/polyfills/require.js:645:37 in setTimeout$argument_0

Unsupported Tailwind class: "pt-12"
at node_modules/tailwind-rn/dist/create.js:35:28 in tailwind
at node_modules/react-native/Libraries/Core/setUpReactRefresh.js:43:45 in Refresh.performReactRefresh
at node_modules/metro-runtime/src/polyfills/require.js:645:37 in setTimeout$argument_0

Unsupported Tailwind class: "bg-blue-200"
at node_modules/tailwind-rn/dist/create.js:35:28 in tailwind
at node_modules/react-native/Libraries/Core/setUpReactRefresh.js:43:45 in Refresh.performReactRefresh
at node_modules/metro-runtime/src/polyfills/require.js:645:37 in setTimeout$argument_0

Unsupported Tailwind class: "px-3"
at node_modules/tailwind-rn/dist/create.js:35:28 in tailwind
at node_modules/react-native/Libraries/Core/setUpReactRefresh.js:43:45 in Refresh.performReactRefresh
at node_modules/metro-runtime/src/polyfills/require.js:645:37 in setTimeout$argument_0

Unsupported Tailwind class: "items-center"
at node_modules/tailwind-rn/dist/create.js:35:28 in tailwind
at node_modules/react-native/Libraries/Core/setUpReactRefresh.js:43:45 in Refresh.performReactRefresh
at node_modules/metro-runtime/src/polyfills/require.js:645:37 in setTimeout$argument_0

Unsupported Tailwind class: "text-blue-600"
at node_modules/tailwind-rn/dist/create.js:35:28 in tailwind
at node_modules/react-native/Libraries/Core/setUpReactRefresh.js:43:45 in Refresh.performReactRefresh
at node_modules/metro-runtime/src/polyfills/require.js:645:37 in setTimeout$argument_0

Unsupported Tailwind class: "py-1"
at node_modules/tailwind-rn/dist/create.js:35:28 in tailwind
at node_modules/react-native/Libraries/Core/setUpReactRefresh.js:43:45 in Refresh.performReactRefresh
at node_modules/metro-runtime/src/polyfills/require.js:645:37 in setTimeout$argument_0

Unsupported Tailwind class: "rounded-full"
at node_modules/tailwind-rn/dist/create.js:35:28 in tailwind
at node_modules/react-native/Libraries/Core/setUpReactRefresh.js:43:45 in Refresh.performReactRefresh
at node_modules/metro-runtime/src/polyfills/require.js:645:37 in setTimeout$argument_0

Unsupported Tailwind class: "h-full"
at node_modules/tailwind-rn/dist/create.js:35:28 in tailwind
at node_modules/react-native/Libraries/Core/setUpReactRefresh.js:43:45 in Refresh.performReactRefresh
at node_modules/metro-runtime/src/polyfills/require.js:645:37 in setTimeout$argument_0

Unsupported Tailwind class: "pt-12"
at node_modules/tailwind-rn/dist/create.js:35:28 in tailwind
at node_modules/react-native/Libraries/Core/setUpReactRefresh.js:43:45 in Refresh.performReactRefresh
at node_modules/metro-runtime/src/polyfills/require.js:645:37 in setTimeout$argument_0

Unsupported Tailwind class: "items-center"
at node_modules/tailwind-rn/dist/create.js:35:28 in tailwind
at node_modules/react-native/Libraries/Core/setUpReactRefresh.js:43:45 in Refresh.performReactRefresh
at node_modules/metro-runtime/src/polyfills/require.js:645:37 in setTimeout$argument_0

Unsupported Tailwind class: "bg-blue-200"
at node_modules/tailwind-rn/dist/create.js:35:28 in tailwind
at node_modules/react-native/Libraries/Core/setUpReactRefresh.js:43:45 in Refresh.performReactRefresh
at node_modules/metro-runtime/src/polyfills/require.js:645:37 in setTimeout$argument_0

Unsupported Tailwind class: "px-3"
at node_modules/tailwind-rn/dist/create.js:35:28 in tailwind
at node_modules/react-native/Libraries/Core/setUpReactRefresh.js:43:45 in Refresh.performReactRefresh
at node_modules/metro-runtime/src/polyfills/require.js:645:37 in setTimeout$argument_0

Unsupported Tailwind class: "py-1"
at node_modules/tailwind-rn/dist/create.js:35:28 in tailwind
at node_modules/react-native/Libraries/Core/setUpReactRefresh.js:43:45 in Refresh.performReactRefresh
at node_modules/metro-runtime/src/polyfills/require.js:645:37 in setTimeout$argument_0

Unsupported Tailwind class: "rounded-full"
at node_modules/tailwind-rn/dist/create.js:35:28 in tailwind
at node_modules/react-native/Libraries/Core/setUpReactRefresh.js:43:45 in Refresh.performReactRefresh
at node_modules/metro-runtime/src/polyfills/require.js:645:37 in setTimeout$argument_0

Unsupported Tailwind class: "text-blue-600"
at node_modules/tailwind-rn/dist/create.js:35:28 in tailwind
at node_modules/react-native/Libraries/Core/setUpReactRefresh.js:43:45 in Refresh.performReactRefresh
at node_modules/metro-runtime/src/polyfills/require.js:645:37 in setTimeout$argument_0

**Comment by tanzeel152** [comment]
yarn dev:tailwind  solved my issue

**Comment by mashwishi** [comment]
up for this issue

**Comment by SorenJ89** [comment]
This started happening to me as well. On a project that has worked for several weeks :(

> yarn dev:tailwind solved my issue

I was already doing this.

my tailwind.config.js looks like this
![image](https://user-images.githubusercontent.com/25386745/220199456-71f22658-8bd0-4e51-af4a-34e2a77c615c.png)

And all my components are inside "screens"
![image](https://user-images.githubusercontent.com/25386745/220199542-eefcb954-50ac-470c-b816-585c0fe0bcef.png)

for some reason my tailwind.css only contain very specific colors
![image](https://user-images.githubusercontent.com/25386745/220199730-adc26152-1c63-461c-b301-922253c4554f.png)

**Comment by SorenJ89** [comment]
Well i found out my issue. I thought i was smart and allowed the parent component to switch the color scheme through a color selection prop.
![image](https://user-images.githubusercontent.com/25386745/220201363-655f78b7-2b6b-4644-ba61-f1611b1d5418.png)

This worked all fine since the color was already defined in tailwind.css, but when the css file got cleared somehow, tailwind woudn't define the bg-gray-400 because of course it didn't know i was using it until my code ran..

Lesson learned.

**Comment by MaximeVictoir** [comment]
I'm running in the same problem. I am using npm run dev:tailwind but I keep on getting: Unsupported Tailwind class: "h-full".
I wrapped the root of the app as such:
    <NavigationContainer>
      <TailwindProvider utilities={utilities}>
        <Stack.Navigator>
          <Stack.Screen options={{headerShown: false}} name="welcome" component={WelcomeScreen} />
          <Stack.Screen options={{headerShown: false}} name="login" component={LoginScreen} />
          <Stack.Screen options={{headerShown: false}} name="forgotpassword" component={ForgotPassword} />
          <Stack.Screen options={{headerShown: false}} name="register" component={Registration} />
          <Stack.Screen options={{headerShown: false}} name="home" component={HomePage} />
        </Stack.Navigator>
      </TailwindProvider>
    </NavigationContainer>
But I still end up with the same error message for any tailwind class

**Comment by Hadiqaa** [comment]
Hi Guys
Has  anyone found a solution to this issue ? 
I have tried npm run dev:tailwind
but still I keep getting this error on every tailwind class I am using !!
