### ISSUE TITLE
Error running `npx create-tailwind-rn`

### ISSUE THREAD

**Issue by buitrbao222** [vadimdemedes/tailwind-rn#90]
I'm using Expo SDK version 42.0.1

This error occurs when i run `npx create-tailwind-rn`:

```
> Error occurred while generating styles
Error: PostCSS plugin postcss-nested requires PostCSS 8.
Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
    at Processor.normalize (D:\Coding\Projects\medofa-app\node_modules\postcss\lib\processor.js:167:15)
    at new Processor (D:\Coding\Projects\medofa-app\node_modules\postcss\lib\processor.js:56:25)
    at postcss (D:\Coding\Projects\medofa-app\node_modules\postcss\lib\postcss.js:55:10)
    at D:\Coding\Projects\medofa-app\node_modules\tailwindcss\lib\util\parseObjectStyles.js:24:33
    at arrayMap (D:\Coding\Projects\medofa-app\node_modules\lodash\lodash.js:653:23)
    at map (D:\Coding\Projects\medofa-app\node_modules\lodash\lodash.js:9622:14)
    at Function.flatMap (D:\Coding\Projects\medofa-app\node_modules\lodash\lodash.js:9325:26)
    at parseObjectStyles (D:\Coding\Projects\medofa-app\node_modules\tailwindcss\lib\util\parseObjectStyles.js:23:26)
    at parseObjectStyles (D:\Coding\Projects\medofa-app\node_modules\tailwindcss\lib\util\parseObjectStyles.js:20:12)
    at D:\Coding\Projects\medofa-app\node_modules\tailwindcss\lib\util\processPlugins.js:39:123
```

What should i do?

**Comment by buitrbao222** [comment]
I installed `postcss` and the error is gone.
